# Datasource
quarkus.datasource.db-kind=mysql
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/demo_db?useSSL=false&serverTimezone=UTC
quarkus.datasource.username=demo
quarkus.datasource.password=roots

# Hibernate ORM
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true
quarkus.log.level=INFO