# Datasource
quarkus.datasource.db-kind=mysql
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/demo_db?useSSL=false&serverTimezone=UTC
quarkus.datasource.username=demo
quarkus.datasource.password=roots

# Hibernate ORM
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

# Configuración de logs
quarkus.log.level=INFO

# Configuración de pruebas de vida
quarkus.smallrye-health.root-path=/health
quarkus.smallrye-health.liveness-path=/live
quarkus.smallrye-health.readiness-path=/ready

